name: Docker Image CI for PRs

on:
  push:
  pull_request:
    branches: [ master ]

jobs:

  test_build:

    runs-on: ubuntu-latest

    steps:

      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build PDNS Recursor latest
        id: docker_build_recursor_latest
        uses: docker/build-push-action@v3
        with:
          context: ./pdns-recursor
          file: ./pdns-recursor/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          builder: ${{ steps.buildx.outputs.name }}
          push: false
          tags: pdns-recursor:latest

      - name: Image digest
        run: echo ${{ steps.docker_build_recursor_latest.outputs.digest }}

      - name: Build PDNS Recursor alpine
        id: docker_build_recursor_alpine
        uses: docker/build-push-action@v3
        with:
          context: ./pdns-recursor
          file: ./pdns-recursor/Dockerfile.alpine
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          builder: ${{ steps.buildx.outputs.name }}
          push: false
          tags: pdns-recursor:alpine

      - name: Image digest
        run: echo ${{ steps.docker_build_recursor_alpine.outputs.digest }}

      - name: Build PDNS latest
        id: docker_build_pdns_latest
        uses: docker/build-push-action@v3
        with:
          context: ./pdns
          file: ./pdns/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          builder: ${{ steps.buildx.outputs.name }}
          push: false
          tags: pdns-mysql:latest

      - name: Image digest
        run: echo ${{ steps.docker_build_pdns_latest.outputs.digest }}

      - name: Build PDNS alpine
        id: docker_build_pdns_alpine
        uses: docker/build-push-action@v3
        with:
          context: ./pdns
          file: ./pdns/Dockerfile.alpine
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          builder: ${{ steps.buildx.outputs.name }}
          push: false
          tags: pdns-mysql:alpine

      - name: Image digest
        run: echo ${{ steps.docker_build_pdns_alpine.outputs.digest }}

      - name: Build admin base
        id: docker_build_admin_base
        uses: docker/build-push-action@v3
        with:
          context: ./pdns-admin-base-ngoduykhanh
          file: ./pdns-admin-base-ngoduykhanh/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          builder: ${{ steps.buildx.outputs.name }}
          push: false
          tags: |
            pdns-admin-base:latest
            pdns-admin-base:ngoduykhanh

      - name: Image digest
        run: echo ${{ steps.docker_build_admin_base.outputs.digest }}

      - name: Build admin uwsgi
        id: docker_build_admin_uwsgi
        uses: docker/build-push-action@v3
        with:
          context: ./pdns-admin-uwsgi-ngoduykhanh
          file: ./pdns-admin-uwsgi-ngoduykhanh/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          builder: ${{ steps.buildx.outputs.name }}
          push: false
          tags: |
            pdns-admin-uwsgi:latest
            pdns-admin-uwsgi:ngoduykhanh

      - name: Image digest
        run: echo ${{ steps.docker_build_admin_uwsgi.outputs.digest }}

      - name: Build admin static
        id: docker_build_admin_static
        uses: docker/build-push-action@v3
        with:
          context: ./pdns-admin-static-ngoduykhanh
          file: ./pdns-admin-static-ngoduykhanh/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          builder: ${{ steps.buildx.outputs.name }}
          push: false
          tags: |
            pdns-admin-static:latest
            pdns-admin-static:ngoduykhanh

      - name: Image digest
        run: echo ${{ steps.docker_build_admin_static.outputs.digest }}
