name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:

  build-recursor-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push PDNS Recursor latest
        id: docker_build_recursor_latest
        uses: docker/build-push-action@v5
        with:
          context: ./pdns-recursor
          file: ./pdns-recursor/Dockerfile
          platforms: linux/amd64,linux/arm64
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pdns-recursor:latest
      - name: Image digest
        run: echo ${{ steps.docker_build_recursor_latest.outputs.digest }}

  build-recursor-alpine:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push PDNS Recursor alpine
        id: docker_build_recursor_alpine
        uses: docker/build-push-action@v5
        with:
          context: ./pdns-recursor
          file: ./pdns-recursor/Dockerfile.alpine
          platforms: linux/amd64,linux/arm64
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pdns-recursor:alpine
      - name: Image digest
        run: echo ${{ steps.docker_build_recursor_alpine.outputs.digest }}

  build-pdns-mysql-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push PDNS mysql latest
        id: docker_build_pdns_mysql_latest
        uses: docker/build-push-action@v5
        with:
          context: ./pdns-mysql
          file: ./pdns-mysql/Dockerfile
          platforms: linux/amd64,linux/arm64
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pdns-mysql:latest
      - name: Image digest
        run: echo ${{ steps.docker_build_pdns_mysql_latest.outputs.digest }}

  build-pdns-mysql-alpine:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push PDNS mysql alpine
        id: docker_build_pdns_mysql_alpine
        uses: docker/build-push-action@v5
        with:
          context: ./pdns-mysql
          file: ./pdns-mysql/Dockerfile.alpine
          platforms: linux/amd64,linux/arm64
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pdns-mysql:alpine
      - name: Image digest
        run: echo ${{ steps.docker_build_pdns_mysql_alpine.outputs.digest }}

  build-pdns-pgsql-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push PDNS pgsql latest
        id: docker_build_pdns_pgsql_latest
        uses: docker/build-push-action@v5
        with:
          context: ./pdns-pgsql
          file: ./pdns-pgsql/Dockerfile
          platforms: linux/amd64,linux/arm64
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pdns-pgsql:latest
      - name: Image digest
        run: echo ${{ steps.docker_build_pdns_pgsql_latest.outputs.digest }}

  build-pdns-pgsql-alpine:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push PDNS pgsql alpine
        id: docker_build_pdns_pgsql_alpine
        uses: docker/build-push-action@v5
        with:
          context: ./pdns-pgsql
          file: ./pdns-pgsql/Dockerfile.alpine
          platforms: linux/amd64,linux/arm64
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pdns-pgsql:alpine
      - name: Image digest
        run: echo ${{ steps.docker_build_pdns_pgsql_alpine.outputs.digest }}

  build-pdns-admin:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push pdns admin
        id: docker_build_pdns_admin
        uses: docker/build-push-action@v5
        with:
          context: ./pdns-admin
          file: ./pdns-admin/Dockerfile
          platforms: linux/amd64,linux/arm64
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/pdns-admin:latest
      - name: Image digest
        run: echo ${{ steps.docker_build_pdns_admin.outputs.digest }}
